# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: ${APP_NAME}-${ENV_NAME}
    image: ${APP_NAME}:${ENV_NAME}
    build: .
    command: gunicorn -w 1 -k uvicorn.workers.UvicornH11Worker -b 0.0.0.0:8001 app.main:app
    env_file:
      - .env
    ports:
      - "${EXTERNAL_PORT}:8001"
    depends_on:
      # - rabbitmq
      - mongo
      - mongo-express
    networks:
      # - host
      - producer_host
  consumer:
    image: ${APP_NAME}
    build: .
    command: python ./app/receive.py
    networks:
      # - host
      - producer_host
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
    # - host
      - producer_host
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
        # - host
        - producer_host
  # extra_hosts:
  #     - "host.docker.internal:host-gateway"
networks:
  producer_host:
    external: true
  # host: