# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: ${APP_NAME}-${ENV_NAME}
    image: ${APP_NAME}:${ENV_NAME}
    build: .
    command: gunicorn -w 1 -k uvicorn.workers.UvicornH11Worker -b 0.0.0.0:8001 app.main:app
    env_file:
      - .env
    ports:
      - "${EXTERNAL_PORT}:8001"
    depends_on:
      - mongo
      - mongo-express
    networks:
      - producer_host
  consumer:
    image: ${APP_NAME}
    build: .
    command: python -u ./receive.py
    networks:
      - producer_host
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - producer_host
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_DB}
    networks:
        - producer_host
networks:
  producer_host:
    external: true
