services:
  web:
    build:
      context: producer-frontend
      target: dev-envs
    ports:
      - 4200:4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./producer-frontend:/project
      - /project/node_modules
